### ISSUE TITLE
Blank class sheet printing

### ISSUE THREAD

**Issue by davidsmpsn** [ShowPanda/ShowBase#33]
Can't figure out where to put the definition for generate_pdf for this as there is no model file for reports. Any ideas? If you click on the print button it will show you the error.

**Comment by trombonebiker** [comment]
There's no `Report` object in the database, and you can't have a model of a non-existent object. Best thing to do is to put it in `app/models/application.rb` and call it something unique to the whole application (i.e. not `generate_pdf` as that's in the cards model file)

**Comment by davidsmpsn** [comment]
I've got it to print something now but I can't work out how to pass the variables through from the categories print job to the pdf template. I think it needs to go in the `:locals => {:sections => self}` bit?

**Comment by trombonebiker** [comment]
I think that `self` might not be defined here? Also in `app/views/reports/categories_pdf.html.erb` you've got an html `head` tag which means that that page will have two `head`s because every page in the app is rendered through `app/views/layouts/application.html.erb` on line 17, which might be causing some problems too.

In the print categories job you can put everything you've got in the `create_pdf` method in the `perform` method, that way it'll be easier to execute it all in one method call and there won't be any issues with variables being rewritten by other methods before the job is actually performed.
